## 2.1 Зачем при изучении Pandas нужен Numpy?

Контейнеры из библиотеки numpy называются **массивами** 

In [5]:
import numpy as np # Импортируем библиотеку

arr = np.arange(100_000_000)
arr

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

* Массивы из библиотеки Numpy работают быстрее в 10-100 раз чем наши любимые питоновские списки (list).  А еще они сильно меньше потребляют оперативной памяти. Это важно, когда мы работаем с реальными проектами.  


* Numpy лег в основу многих библиотек для анализа данных и машинного обучения.

**Создание массива:**

In [2]:
import numpy as np

lst = [1, 2, 3, 4, 5.2]
arr1 = np.array(lst) # принимает список
arr1

array([1. , 2. , 3. , 4. , 5.2])

Можно передавать вложенные списки

In [6]:
arr2 = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
arr2


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

Свойство **shape** (переводится как форма) - показывает размер каждого измерений.  
* Если у вас shape = (4,) это значит, что у вас одномерный массив длинной 4
* Если у вас shape = (2, 3) это значит, что у вас двумерный массив (массив, который состоит из подмассивов). Каждый подмассив длинной 3.  
* Если у вас shape = (4, 3, 2) это значит, что у вас трехмерный массив. Но из чего он состоит? Представьте себе двумерный массив размером (3, 2). Вот таких двухмерных массивов (называют матрицами) у вас будет 4.

In [28]:
arr2.shape

(3, 3)

С помощью стандартной функции **len** можно получить только количество подмассивов в массиве.

In [29]:
len(arr2)

3

Свойство **ndim** - сокращение от number of dimensions (переводится как количество измерений).  Поможет ответить на вопрос: а сколько измерений в моем массиве (какая вложенность)?  
* Если ndim =1 значит у вас 1D array (см. выше). Он же одномерный массив.
* Если ndim =2 значит у вас 2D array (см. выше). Он же двумерный массив. Она же матрица.
* Если ndim =3 значит у вас 3D array (см. выше). 

In [34]:
arr2.ndim

2

Когда вы создаете массив, Numpy пытается понять из каких элементов вы пытаетесь его создать и подбирает **наиболее подходящий тип данных.** Свойство **dtype** подскажет, какой тип данных у каждого элемента вашего массива

In [36]:
arr.dtype

dtype('int32')

Часто на практике надо создать массив, который предварительно заполнен нулями. Функция **zeros** поможет нам в этом!  

Если в функцию **zeros** передать просто число, тогда будет создан одномерный массив

In [43]:
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

Если в функцию **zeros** передать кортеж из двух чисел, например zeros((3, 2)), тогда будет создана матрица с тремя строками и двумя столбцами. (или если вам проще: будет создан массив, в котором будет три подмассива, где каждый подмассив будет на два элемента)

In [54]:
arr2 = np.zeros((3, 2))
arr2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Аналогичная функция - **ones**, но для 1

In [57]:
arr2 = np.ones((3, 2))
arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Функция **full** еще лучше, т.к. с помощью нее можно инциализировать любое значение

In [8]:
arr2 = np.full((3, 2), -5)
arr2

array([[-5, -5],
       [-5, -5],
       [-5, -5]])

Функция **arange** аналогична встроенной функции **range** и заполняет массив данными

In [64]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

# Задачи урока 2.1

1. Напишите функцию, которая возвращает numpy массив на основе предложенного списка (lst).

In [69]:
import numpy as np

def solution(lst):
    arr = np.array(lst)
    return arr

solution([1, 2, 3])

array([1, 2, 3])

2. Напишите функцию, которая возвращает одномерный массив длинной 100 и заполненный нулями.

In [70]:
import numpy as np

def solution():
    arr = np.zeros(100)
    return arr

print(solution())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


## 2.2 Практика: shape, dtype, ndim, zeros, ones, arange

1. Создайте массив заполненный нулями у которого shape = (2, 5)

In [1]:
import numpy as np

def solution():
    arr = np.zeros((2, 5))
    return arr


print(solution())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2. Создайте массив заполненный единицами у которого 5 строк и 8 столбцов (5 вложенных массивов длинной 8)

In [4]:
import numpy as np

def solution():
    arr = np.ones((5, 8))
    return arr

solution()

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

3. Создайте одномерный numpy массив со значениями 0, 1, 2, .... 99 (диапазон значений от 0 до 99)

In [5]:
import numpy as np

def solution():
    arr = np.arange(100)
    return arr


solution()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

4. Создайте двумерный массив размером 5 х 2, который полностью будет заполнен значением 'G' 

In [ ]:
import numpy as np

def solution():
    arr = np.full((5, 2), 'G')
    return arr


solution()

## 2.3 Типы данных и их преобразование, арифметика, доступ к элементам

Функция **array** может принимать второй необязательный аргумент **dtype** для формирования массива с определённым типом данных

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)

print(new_arr.dtype)

int64


Функция **astype** выполнит преобразование типов и вернет новый массив с новым типом данных.

In [13]:
new_arr = arr.astype(np.int64)

print(new_arr.dtype, arr.dtype)

int64 float64


Если вы поменяете тип данных с **float_** на **int_**, то numpy отрежет десятичную часть от каждого числа и оставит только целую. Округления не будет! Округление делается по другому.

In [16]:
import numpy as np

arr = np.array([1.5, 2.5, 3.1, 4.2, 5.8], dtype=np.float64)

print(arr.astype(np.int32))

[1 2 3 4 5]


### Арифметические операции в NumPy

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# сложение
print(arr + arr)
print(arr + 1, end='\n\n')

# разность
print(arr - arr)
print(arr - 1, end='\n\n')

# умножение
print(arr * arr)
print(arr * 2, end='\n\n')

# деление
print(arr / arr)
print(arr / 2, end='\n\n')
 
# возведение в степень
print(arr ** arr)
print(arr ** 2)

[ 2  4  6  8 10]
[2 3 4 5 6]

[0 0 0 0 0]
[0 1 2 3 4]

[ 1  4  9 16 25]
[ 2  4  6  8 10]

[1. 1. 1. 1. 1.]
[0.5 1.  1.5 2.  2.5]

[   1    4   27  256 3125]
[ 1  4  9 16 25]


### Сравнение элементов между массивами

Если необходимо сравнить два массива поэлементно, то не нужно писать цикл! Достаточно просто написать:

In [34]:
import numpy as np

m1 = np.array([36.6, 36.5, 37.0])
m2 = np.array([36.9, 36.5, 35.6])

print(m1 > m2)
print(m1 < m2)
print(m1 <= m2)
print(m1 >= m2)
print(m1 == m2)
print(m1 != m2)

[False False  True]
[ True False False]
[ True  True False]
[False  True  True]
[False  True False]
[ True False  True]


### Доступ к элементам массива

Для доступа к одному элементу массива указываем индекс этого элемента в квадратных скобках, а для получения доступа к нескольким элементам указываем диапазон через двоеточие

In [36]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])

print(m[2])
print(m[2:4])
print(m[-1])

3
[3 4]
5


Массивы как и списки в Python **изменяемые**, поэтому если мы поменяли элемент в массиве, то он изменится во всех связанных массивах

### Задачи урока 2.2

1. Напишите функцию, которая на основе существующего списка создает numpy массив с типом float64

In [40]:
import numpy as np

def solution(lst):
    arr = np.array(lst, dtype=np.float64)
    return arr


print(solution([1, 2, 3, 4, 5]))

[1. 2. 3. 4. 5.]


2. К вам в распоряжение поступает массив arr с типом float64. Преобразуйте, пожалуйста, в int32

In [100]:
import numpy as np

def solution(arr):
    arr = arr.astype(np.int32)
    return arr


print(solution(np.array([1.5, 2.3, 4.3])))

[1 2 4]


## 2.4 Практика: арифметика, преобразование типов, доступ к элементам

1. На вход подается одномерный массив со значениями от 0 до 5 (включительно). Примените некоторую операцию  чтобы на выходе получился массив со значениями 1000, 1001....1005

In [16]:
import numpy as np

def solution(arr):
    arr = arr + 1000
    return arr


print(solution(np.array([0, 1, 2, 3, 4, 5])))

[1000 1001 1002 1003 1004 1005]


2. На вход подается одномерный массив в котором хранится информация о количестве картофеля на каждом складе (всего 5 складов). Посчитайте для каждого склада, сколько процентов картофеля от общего количества хранится на каждом складе. Общее количество картофеля на всех складах 115 кг. Не забудьте что каждое значение надо умножить на 100. Округлять значения не требуется! Знак процента тоже добавлять не следует. Просто выполните арифметические операции.

In [98]:
import numpy as np

def solution(arr):
    arr = arr / sum(arr) * 100
    return arr


print(solution(np.array([30, 40, 30, 10, 5])))

[26.08695652 34.7826087  26.08695652  8.69565217  4.34782609]


3. Выполните действия:

   1) Создайте одномерный массив со значениями в диапазоне от 0 до 10 (включительно). 

   2) Создайте второй одномерный массив со значениями в диапазоне от 10 до 20 (включительно). 

   3) Вычтите из второго массива первый. 

   4) Проверьте каждое значение получившегося массива на равенство значению 10. Результат сравнения верните в отдельном numpy массиве.

In [97]:
import numpy as np

def solution():
    arr = np.arange(11)
    arr2 = np.arange(10, 21)
    return (arr2 - arr) == 10


solution()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

4. Во входящем массиве arr содержится информация о водителях, которые превысили скорость на некотором участке дороги. Определите насколько каждый водитель превысил скорость, если допустимая скорость равна 80. Результаты представьте в отдельном numpy массиве

In [58]:
import numpy as np

solution = lambda arr: arr - 80

solution(np.array([100, 120, 99]))

array([20, 40, 19])

5. На вход вашей функции подается некоторый одномерный массив. Предполагается, что там лежат числа с плавающей точкой, но записаны они как строка. Выполните сложение элементов с индексами 1 и 3. На выходе ваша функция должна вернуть число (сумма двух элементов массива).

In [10]:
import numpy as np

def solution(arr):
    arr = arr.astype('float64')
    return arr[1] + arr[3]


print(solution(np.array(['5.1', '8.2', '4.3', '9.4', '10.5'])))

17.6


6. На вход вашей функции подается два одномерных массива. Сложите первые два элемента первого массива с последними двумя элементами второго массива (поэлементно). На выходе должен получится новый одномерный массив, который будет хранить два значения

In [9]:
import numpy as np

def solution(arr1, arr2):
    return arr1[:2] + arr2[-2:]


solution(np.array([1, 2, 3]), np.array([4, 5, 6]))

array([6, 8])

7. На вход подается некоторый одномерный массив. Занулите первые 3 элемента.

In [8]:
import numpy as np

def solution(arr):
    arr[:3] = 0
    return arr


print(solution(np.array([1, 2, 3, 4, 5])))

[0 0 0 4 5]


## 2.5 Двумерные и трехмерные массивы. Учимся применять индексы

### Индексация одномерного массива

Если из массива необходимо вытянуть часть данных с помощью среза (слайсинга), то необходимо использовать метод **copy()**, т.к. при слайсинге мы копируем не объект, а делаем ссылку на него

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = arr[2:4]
new_arr[0] = 10

print(arr)

[ 1  2 10  4  5]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = arr[2:4].copy()
new_arr[0] = 10

print(arr, new_arr, sep='\n')

[1 2 3 4 5]
[10  4]


### Индексация двумерного массива

Обратиться к элементу вложенного массива можно 2 способами. 1 вариант через индексацию, как в стандартном Python, 2 вариант через индексацию NumpPy

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])

print(arr[1][3])
print(arr[1, 3])

40
40


### Индексация трехмерного массива

In [31]:
import numpy as np

arr = np.array([[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]], [[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]])

print(arr[0][1][1]) # Python вариант
print(arr[0, 1, 1]) # NumPy вариант

arr[0][1] = 0 # Замента всех значений на 0
print(arr, end='\n\n')

20
20
[[[ 1  2  3  4  5]
  [ 0  0  0  0  0]]

 [[ 1  2  3  4  5]
  [10 20 30 40 50]]]



### Слайсинг в NumPy

Если необходимо вытянуть данные по определенному "Столбцу" или "Строке", в слайсинге сначала указывается выборка по строке, а потом по столбцу

In [99]:
import numpy as np

m = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [11, 22, 33, 44, 55]])

print(m[:, 2], end='\n\n')
print(m[:, 2:4], end='\n\n')
print(m[0:2, 0:2])

[ 3 30 33]

[[ 3  4]
 [30 40]
 [33 44]]

[[ 1  2]
 [10 20]]


### Индексация с Mask

**Маска** - это массив (одномерный или многомерный), который состоит из булевых значений. Если True - то элемент будет вытянут, если False - нет.

In [96]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]

print(m[mask])

[1 3 5]


Важно запомнить, что возвращается массив, который не содержит ссылку на исходный массив, т.е. он скопирован

**Маски очень удобно использовать для фильтрации данных, примеры:**

In [55]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])
mask = m > 2

print(m[mask])
print(m[m < 3])

[3 4 5]
[1 2]


In [75]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = users == 'Вадим'

print(visits[mask])

[[1 1 2 0 1 0 1]]


### Задачи урока 2.5

1. На вход подается двумерный массив (матрица), вытяните из матрицы указанную область.:

![1](https://ucarecdn.com/d2707fa4-3105-46da-a1d7-0a4ca4e40362/)



In [81]:
import numpy as np

def solution(arr):
    arr = arr[:2, :2]
    return arr

2. На вход подается двумерный массив (матрица), вытяните из матрицы указанную область.

![1](https://ucarecdn.com/7f96bccf-dce4-430f-8f5e-9842a24b5000/)

In [84]:
import numpy as np

def solution(arr):
    arr = arr[1:3, 3:]
    return arr

## 2.6 Практика: закрепляем работу с индексами

1. Выполните поэлементное сложение двух столбцов:

![1](https://ucarecdn.com/1d6c0c70-0f78-4827-8f21-072923404f5d/)

In [91]:
import numpy as np

def solution(arr):
    arr = arr[:, 0] + arr[:, 3]
    return arr


arr1 = np.array([[10, 12, 14, 18, 20],
                 [8,  22, 18, 19, 12],
                 [4,  14, 84, 38, 11],
                 [2,  32, 4,  31,  9],
                 [1,  11, 1,  8,  6]])

solution(arr1)

array([28, 27, 42, 33,  9])

2. Выполните поэлементное сложение двух строк:

![1](https://ucarecdn.com/7531165c-7236-4a03-af90-970f76bdf2e1/)

In [92]:
import numpy as np

def solution(arr):
    arr = arr[1] + arr[3]
    return arr

3. Выполните поэлементное сложение двух столбцов:

![1](https://ucarecdn.com/7a2be0a9-154f-4324-a1c3-86413db31247/)

In [94]:
import numpy as np

def solution(arr):
    arr = arr[1:4, 1] + arr[1:4, 3]
    return arr

4.  Выполните поэлементное сложение двух строк:

![1](https://ucarecdn.com/2f1ff817-4521-44d2-8b96-bf866ef9e932/)

In [97]:
import numpy as np

def solution(arr):
    arr = arr[0, :-1] + arr[-1, 1:]
    return arr

5.  Выполните поэлементное сложение двух столбцов:

![1](https://ucarecdn.com/faa3d37f-a16c-49b0-aeb7-e45512d9dcf7/)

In [100]:
import numpy as np

def solution(arr):
    arr = arr[1:-1, 1] + arr[2:, 2]
    return arr

6. Выполните поэлементное сложение двух матриц:

![1](https://ucarecdn.com/2bf71390-a37e-4420-a0e9-27f3b3ce6b06/)

In [ ]:
import numpy as np

def solution(arr):
    arr = arr[2:, :2] + arr[:-2, -2:]
    return arr

7. Выполните поэлементное сравнение двух столбцов, если значение в первом столбце больше чем значение во втором, тогда в результирующем массиве должно быть True, иначе False:

![1](https://ucarecdn.com/21f66abd-1a69-444c-9138-eeaf8d9d54de/)

In [1]:
import numpy as np

def solution(arr):
    arr = arr[:, 0] > arr[:, 2]
    return arr


m = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

solution(m)

array([False, False, False, False, False, False])

## 2.7 Маска и слайсинг вместе, прихотливая индексация, а еще reshape

В скобках можно работать и с маской и с индексами одновременно!

In [14]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = users == 'Вадим'

print(visits[mask, 5:])

[[0 1]]


Если вы хотите выполнить инверсию булевых значений(True заменить на False, а False на True), то не стоит использовать команду not. Для этого есть знак ~ (тильда). На клавиатуре ищите рядом с буквой Ё.

In [16]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = users == 'Вадим'

print(visits[~mask])

[[1 0 1 0 1 0 2]
 [1 3 2 1 1 0 1]
 [0 1 2 2 1 0 0]
 [0 1 1 2 1 1 0]]


При работе с numpy для логических операций вы не работаете со стандартными питоновскими and и or. У numpy свои операторы:
1. Логическое ИЛИ:   |  (ищите выше клавиши Enter)
2. Логическое И:  & (ищите на клавише с цифрой 7)  

In [28]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = (users == 'Вадим') | (users == 'Илья')

print(visits[mask], end='\n\n')
print(visits[~mask])

[[1 1 2 0 1 0 1]
 [1 3 2 1 1 0 1]]

[[1 0 1 0 1 0 2]
 [0 1 2 2 1 0 0]
 [0 1 1 2 1 1 0]]


Можно вытягивать данные с помощью **прихотливой индексации**.
Алгоритм таков: передаем список/массив с индексами по которым надо вытащить значения. Индексы могут идти не по порядку.

In [40]:
import numpy as np

m = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

print(m[[2, 4, 1], 1:], end='\n\n')
print(m[[0, 2, 4], [1, 2, 3]])

[[11 12 13 14]
 [21 22 23 24]
 [ 6  7  8  9]]

[ 1 12 23]


Функция **reshape** позволяет преобразовать массив данных в определенное кол-во подмассивов с нужным кол-вом элементов. В функцию передается кортеж, где первым элементом является кол-во строк, а втором кол-во столбцов, их произведение должно равнятся количеству всех элементов в исходном массиве

In [52]:
import numpy as np

m = np.arange(100)

print(m.reshape((5, 20)), end='\n\n') # двумерный вариант
print(m.reshape((5, 2, 10))) # трёхмерный вариант

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


### Задачи урока 2.7

1. На вход функции подается двумерный массив, доработайте функцию так чтобы она вернула маску по которой потом можно будет выбрать значения меньше 20 или больше 40.

![1](https://ucarecdn.com/49ccd304-d7b8-4203-9457-1cf4338b4056/)

In [87]:
import numpy as np

def solution(arr):
    mask = (arr < 20) | (arr > 40)
    return mask

2. На вход функции подается двумерный массив, доработайте функцию так чтобы она вернула значения, которые лежат на главной диагонали. Значения должны быть в одномерном массиве (Для особых знатоков: функцией diag не пользоваться!). Работайте с прихотливой индексацией.

![1](https://ucarecdn.com/62de17b8-9f2b-41e1-964e-736642e80acc/)

In [74]:
import numpy as np

def solution(arr):
    arr = arr[range(5), range(5)]
    return arr

3. На вход функции подается двумерный массив, доработайте функцию так чтобы она вернула значения, которые лежат на побочной диагонали. Значения должны быть в одномерном массиве array([1, 32, 84, 19, 20]) (Для особых знатоков: функцией diag не пользоваться!). Работайте с прихотливой индексацией.

![1](https://ucarecdn.com/3bb5b4e9-f8bf-4230-be95-304d24c5ae1f/)

In [86]:
import numpy as np

def solution(arr):
    arr = arr[range(4, -1, -1), range(5)]
    return arr