## 2.1 Зачем при изучении Pandas нужен Numpy?

Контейнеры из библиотеки numpy называются **массивами** 

In [5]:
import numpy as np # Импортируем библиотеку

arr = np.arange(100_000_000)
arr

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

* Массивы из библиотеки Numpy работают быстрее в 10-100 раз чем наши любимые питоновские списки (list).  А еще они сильно меньше потребляют оперативной памяти. Это важно, когда мы работаем с реальными проектами.  


* Numpy лег в основу многих библиотек для анализа данных и машинного обучения.

**Создание массива:**

In [2]:
import numpy as np

lst = [1, 2, 3, 4, 5.2]
arr1 = np.array(lst) # принимает список
arr1

array([1. , 2. , 3. , 4. , 5.2])

Можно передавать вложенные списки

In [6]:
arr2 = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
arr2


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

Свойство **shape** (переводится как форма) - показывает размер каждого измерений.  
* Если у вас shape = (4,) это значит, что у вас одномерный массив длинной 4
* Если у вас shape = (2, 3) это значит, что у вас двумерный массив (массив, который состоит из подмассивов). Каждый подмассив длинной 3.  
* Если у вас shape = (4, 3, 2) это значит, что у вас трехмерный массив. Но из чего он состоит? Представьте себе двумерный массив размером (3, 2). Вот таких двухмерных массивов (называют матрицами) у вас будет 4.

In [28]:
arr2.shape

(3, 3)

С помощью стандартной функции **len** можно получить только количество подмассивов в массиве.

In [29]:
len(arr2)

3

Свойство **ndim** - сокращение от number of dimensions (переводится как количество измерений).  Поможет ответить на вопрос: а сколько измерений в моем массиве (какая вложенность)?  
* Если ndim =1 значит у вас 1D array (см. выше). Он же одномерный массив.
* Если ndim =2 значит у вас 2D array (см. выше). Он же двумерный массив. Она же матрица.
* Если ndim =3 значит у вас 3D array (см. выше). 

In [34]:
arr2.ndim

2

Когда вы создаете массив, Numpy пытается понять из каких элементов вы пытаетесь его создать и подбирает **наиболее подходящий тип данных.** Свойство **dtype** подскажет, какой тип данных у каждого элемента вашего массива

In [36]:
arr.dtype

dtype('int32')

Часто на практике надо создать массив, который предварительно заполнен нулями. Функция **zeros** поможет нам в этом!  

Если в функцию **zeros** передать просто число, тогда будет создан одномерный массив

In [43]:
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

Если в функцию **zeros** передать кортеж из двух чисел, например zeros((3, 2)), тогда будет создана матрица с тремя строками и двумя столбцами. (или если вам проще: будет создан массив, в котором будет три подмассива, где каждый подмассив будет на два элемента)

In [54]:
arr2 = np.zeros((3, 2))
arr2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Аналогичная функция - **ones**, но для 1

In [57]:
arr2 = np.ones((3, 2))
arr2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Функция **full** еще лучше, т.к. с помощью нее можно инциализировать любое значение

In [8]:
arr2 = np.full((3, 2), -5)
arr2

array([[-5, -5],
       [-5, -5],
       [-5, -5]])

Функция **arange** аналогична встроенной функции **range** и заполняет массив данными

In [64]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

# Задачи урока 2.1

1. Напишите функцию, которая возвращает numpy массив на основе предложенного списка (lst).

In [69]:
import numpy as np

def solution(lst):
    arr = np.array(lst)
    return arr

solution([1, 2, 3])

array([1, 2, 3])

2. Напишите функцию, которая возвращает одномерный массив длинной 100 и заполненный нулями.

In [70]:
import numpy as np

def solution():
    arr = np.zeros(100)
    return arr

print(solution())

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


## 2.2 Практика: shape, dtype, ndim, zeros, ones, arange

1. Создайте массив заполненный нулями у которого shape = (2, 5)

In [1]:
import numpy as np

def solution():
    arr = np.zeros((2, 5))
    return arr


print(solution())

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2. Создайте массив заполненный единицами у которого 5 строк и 8 столбцов (5 вложенных массивов длинной 8)

In [4]:
import numpy as np

def solution():
    arr = np.ones((5, 8))
    return arr

solution()

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

3. Создайте одномерный numpy массив со значениями 0, 1, 2, .... 99 (диапазон значений от 0 до 99)

In [5]:
import numpy as np

def solution():
    arr = np.arange(100)
    return arr


solution()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

4. Создайте двумерный массив размером 5 х 2, который полностью будет заполнен значением 'G' 

In [ ]:
import numpy as np

def solution():
    arr = np.full((5, 2), 'G')
    return arr


solution()

## 2.3 Типы данных и их преобразование, арифметика, доступ к элементам

Функция **array** может принимать второй необязательный аргумент **dtype** для формирования массива с определённым типом данных

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5], dtype=np.float64)

print(new_arr.dtype)

int64


Функция **astype** выполнит преобразование типов и вернет новый массив с новым типом данных.

In [13]:
new_arr = arr.astype(np.int64)

print(new_arr.dtype, arr.dtype)

int64 float64


Если вы поменяете тип данных с **float_** на **int_**, то numpy отрежет десятичную часть от каждого числа и оставит только целую. Округления не будет! Округление делается по другому.

In [16]:
import numpy as np

arr = np.array([1.5, 2.5, 3.1, 4.2, 5.8], dtype=np.float64)

print(arr.astype(np.int32))

[1 2 3 4 5]


### Арифметические операции в NumPy

In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# сложение
print(arr + arr)
print(arr + 1, end='\n\n')

# разность
print(arr - arr)
print(arr - 1, end='\n\n')

# умножение
print(arr * arr)
print(arr * 2, end='\n\n')

# деление
print(arr / arr)
print(arr / 2, end='\n\n')
 
# возведение в степень
print(arr ** arr)
print(arr ** 2)

[ 2  4  6  8 10]
[2 3 4 5 6]

[0 0 0 0 0]
[0 1 2 3 4]

[ 1  4  9 16 25]
[ 2  4  6  8 10]

[1. 1. 1. 1. 1.]
[0.5 1.  1.5 2.  2.5]

[   1    4   27  256 3125]
[ 1  4  9 16 25]


### Сравнение элементов между массивами

Если необходимо сравнить два массива поэлементно, то не нужно писать цикл! Достаточно просто написать:

In [34]:
import numpy as np

m1 = np.array([36.6, 36.5, 37.0])
m2 = np.array([36.9, 36.5, 35.6])

print(m1 > m2)
print(m1 < m2)
print(m1 <= m2)
print(m1 >= m2)
print(m1 == m2)
print(m1 != m2)

[False False  True]
[ True False False]
[ True  True False]
[False  True  True]
[False  True False]
[ True False  True]


### Доступ к элементам массива

Для доступа к одному элементу массива указываем индекс этого элемента в квадратных скобках, а для получения доступа к нескольким элементам указываем диапазон через двоеточие

In [36]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])

print(m[2])
print(m[2:4])
print(m[-1])

3
[3 4]
5


Массивы как и списки в Python **изменяемые**, поэтому если мы поменяли элемент в массиве, то он изменится во всех связанных массивах

### Задачи урока 2.2

1. Напишите функцию, которая на основе существующего списка создает numpy массив с типом float64

In [40]:
import numpy as np

def solution(lst):
    arr = np.array(lst, dtype=np.float64)
    return arr


print(solution([1, 2, 3, 4, 5]))

[1. 2. 3. 4. 5.]


2. К вам в распоряжение поступает массив arr с типом float64. Преобразуйте, пожалуйста, в int32

In [100]:
import numpy as np

def solution(arr):
    arr = arr.astype(np.int32)
    return arr


print(solution(np.array([1.5, 2.3, 4.3])))

[1 2 4]


## 2.4 Практика: арифметика, преобразование типов, доступ к элементам

1. На вход подается одномерный массив со значениями от 0 до 5 (включительно). Примените некоторую операцию  чтобы на выходе получился массив со значениями 1000, 1001....1005

In [16]:
import numpy as np

def solution(arr):
    arr = arr + 1000
    return arr


print(solution(np.array([0, 1, 2, 3, 4, 5])))

[1000 1001 1002 1003 1004 1005]


2. На вход подается одномерный массив в котором хранится информация о количестве картофеля на каждом складе (всего 5 складов). Посчитайте для каждого склада, сколько процентов картофеля от общего количества хранится на каждом складе. Общее количество картофеля на всех складах 115 кг. Не забудьте что каждое значение надо умножить на 100. Округлять значения не требуется! Знак процента тоже добавлять не следует. Просто выполните арифметические операции.

In [98]:
import numpy as np

def solution(arr):
    arr = arr / sum(arr) * 100
    return arr


print(solution(np.array([30, 40, 30, 10, 5])))

[26.08695652 34.7826087  26.08695652  8.69565217  4.34782609]


3. Выполните действия:

   1) Создайте одномерный массив со значениями в диапазоне от 0 до 10 (включительно). 

   2) Создайте второй одномерный массив со значениями в диапазоне от 10 до 20 (включительно). 

   3) Вычтите из второго массива первый. 

   4) Проверьте каждое значение получившегося массива на равенство значению 10. Результат сравнения верните в отдельном numpy массиве.

In [97]:
import numpy as np

def solution():
    arr = np.arange(11)
    arr2 = np.arange(10, 21)
    return (arr2 - arr) == 10


solution()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

4. Во входящем массиве arr содержится информация о водителях, которые превысили скорость на некотором участке дороги. Определите насколько каждый водитель превысил скорость, если допустимая скорость равна 80. Результаты представьте в отдельном numpy массиве

In [58]:
import numpy as np

solution = lambda arr: arr - 80

solution(np.array([100, 120, 99]))

array([20, 40, 19])

5. На вход вашей функции подается некоторый одномерный массив. Предполагается, что там лежат числа с плавающей точкой, но записаны они как строка. Выполните сложение элементов с индексами 1 и 3. На выходе ваша функция должна вернуть число (сумма двух элементов массива).

In [10]:
import numpy as np

def solution(arr):
    arr = arr.astype('float64')
    return arr[1] + arr[3]


print(solution(np.array(['5.1', '8.2', '4.3', '9.4', '10.5'])))

17.6


6. На вход вашей функции подается два одномерных массива. Сложите первые два элемента первого массива с последними двумя элементами второго массива (поэлементно). На выходе должен получится новый одномерный массив, который будет хранить два значения

In [9]:
import numpy as np

def solution(arr1, arr2):
    return arr1[:2] + arr2[-2:]


solution(np.array([1, 2, 3]), np.array([4, 5, 6]))

array([6, 8])

7. На вход подается некоторый одномерный массив. Занулите первые 3 элемента.

In [8]:
import numpy as np

def solution(arr):
    arr[:3] = 0
    return arr


print(solution(np.array([1, 2, 3, 4, 5])))

[0 0 0 4 5]


## 2.5 Двумерные и трехмерные массивы. Учимся применять индексы

### Индексация одномерного массива

Если из массива необходимо вытянуть часть данных с помощью среза (слайсинга), то необходимо использовать метод **copy()**, т.к. при слайсинге мы копируем не объект, а делаем ссылку на него

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = arr[2:4]
new_arr[0] = 10

print(arr)

[ 1  2 10  4  5]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
new_arr = arr[2:4].copy()
new_arr[0] = 10

print(arr, new_arr, sep='\n')

[1 2 3 4 5]
[10  4]


### Индексация двумерного массива

Обратиться к элементу вложенного массива можно 2 способами. 1 вариант через индексацию, как в стандартном Python, 2 вариант через индексацию NumpPy

In [14]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]])

print(arr[1][3])
print(arr[1, 3])

40
40


### Индексация трехмерного массива

In [31]:
import numpy as np

arr = np.array([[[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]], [[1, 2, 3, 4, 5], [10, 20, 30, 40, 50]]])

print(arr[0][1][1]) # Python вариант
print(arr[0, 1, 1]) # NumPy вариант

arr[0][1] = 0 # Замента всех значений на 0
print(arr, end='\n\n')

20
20
[[[ 1  2  3  4  5]
  [ 0  0  0  0  0]]

 [[ 1  2  3  4  5]
  [10 20 30 40 50]]]



### Слайсинг в NumPy

Если необходимо вытянуть данные по определенному "Столбцу" или "Строке", в слайсинге сначала указывается выборка по строке, а потом по столбцу

In [99]:
import numpy as np

m = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [11, 22, 33, 44, 55]])

print(m[:, 2], end='\n\n')
print(m[:, 2:4], end='\n\n')
print(m[0:2, 0:2])

[ 3 30 33]

[[ 3  4]
 [30 40]
 [33 44]]

[[ 1  2]
 [10 20]]


### Индексация с Mask

**Маска** - это массив (одномерный или многомерный), который состоит из булевых значений. Если True - то элемент будет вытянут, если False - нет.

In [96]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])
mask = [True, False, True, False, True]

print(m[mask])

[1 3 5]


Важно запомнить, что возвращается массив, который не содержит ссылку на исходный массив, т.е. он скопирован

**Маски очень удобно использовать для фильтрации данных, примеры:**

In [55]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])
mask = m > 2

print(m[mask])
print(m[m < 3])

[3 4 5]
[1 2]


In [75]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = users == 'Вадим'

print(visits[mask])

[[1 1 2 0 1 0 1]]


### Задачи урока 2.5

1. На вход подается двумерный массив (матрица), вытяните из матрицы указанную область.:

![1](https://ucarecdn.com/d2707fa4-3105-46da-a1d7-0a4ca4e40362/)



In [81]:
import numpy as np

def solution(arr):
    arr = arr[:2, :2]
    return arr

2. На вход подается двумерный массив (матрица), вытяните из матрицы указанную область.

![1](https://ucarecdn.com/7f96bccf-dce4-430f-8f5e-9842a24b5000/)

In [84]:
import numpy as np

def solution(arr):
    arr = arr[1:3, 3:]
    return arr

## 2.6 Практика: закрепляем работу с индексами

1. Выполните поэлементное сложение двух столбцов:

![1](https://ucarecdn.com/1d6c0c70-0f78-4827-8f21-072923404f5d/)

In [91]:
import numpy as np

def solution(arr):
    arr = arr[:, 0] + arr[:, 3]
    return arr


arr1 = np.array([[10, 12, 14, 18, 20],
                 [8,  22, 18, 19, 12],
                 [4,  14, 84, 38, 11],
                 [2,  32, 4,  31,  9],
                 [1,  11, 1,  8,  6]])

solution(arr1)

array([28, 27, 42, 33,  9])

2. Выполните поэлементное сложение двух строк:

![1](https://ucarecdn.com/7531165c-7236-4a03-af90-970f76bdf2e1/)

In [92]:
import numpy as np

def solution(arr):
    arr = arr[1] + arr[3]
    return arr

3. Выполните поэлементное сложение двух столбцов:

![1](https://ucarecdn.com/7a2be0a9-154f-4324-a1c3-86413db31247/)

In [94]:
import numpy as np

def solution(arr):
    arr = arr[1:4, 1] + arr[1:4, 3]
    return arr

4.  Выполните поэлементное сложение двух строк:

![1](https://ucarecdn.com/2f1ff817-4521-44d2-8b96-bf866ef9e932/)

In [97]:
import numpy as np

def solution(arr):
    arr = arr[0, :-1] + arr[-1, 1:]
    return arr

5.  Выполните поэлементное сложение двух столбцов:

![1](https://ucarecdn.com/faa3d37f-a16c-49b0-aeb7-e45512d9dcf7/)

In [100]:
import numpy as np

def solution(arr):
    arr = arr[1:-1, 1] + arr[2:, 2]
    return arr

6. Выполните поэлементное сложение двух матриц:

![1](https://ucarecdn.com/2bf71390-a37e-4420-a0e9-27f3b3ce6b06/)

In [ ]:
import numpy as np

def solution(arr):
    arr = arr[2:, :2] + arr[:-2, -2:]
    return arr

7. Выполните поэлементное сравнение двух столбцов, если значение в первом столбце больше чем значение во втором, тогда в результирующем массиве должно быть True, иначе False:

![1](https://ucarecdn.com/21f66abd-1a69-444c-9138-eeaf8d9d54de/)

In [1]:
import numpy as np

def solution(arr):
    arr = arr[:, 0] > arr[:, 2]
    return arr


m = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

solution(m)

array([False, False, False, False, False, False])

## 2.7 Маска и слайсинг вместе, прихотливая индексация, а еще reshape

В скобках можно работать и с маской и с индексами одновременно!

In [14]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = users == 'Вадим'

print(visits[mask, 5:])

[[0 1]]


Если вы хотите выполнить инверсию булевых значений(True заменить на False, а False на True), то не стоит использовать команду not. Для этого есть знак ~ (тильда). На клавиатуре ищите рядом с буквой Ё.

In [16]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = users == 'Вадим'

print(visits[~mask])

[[1 0 1 0 1 0 2]
 [1 3 2 1 1 0 1]
 [0 1 2 2 1 0 0]
 [0 1 1 2 1 1 0]]


При работе с numpy для логических операций вы не работаете со стандартными питоновскими and и or. У numpy свои операторы:
1. Логическое ИЛИ:   |  (ищите выше клавиши Enter)
2. Логическое И:  & (ищите на клавише с цифрой 7)  

In [28]:
import numpy as np

users = np.array(['Вадим', 'Ян', 'Илья', 'Рома', 'Алексей'])
visits = np.array([[1, 1, 2, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 2], [1, 3, 2, 1, 1, 0, 1], [0, 1, 2, 2, 1, 0, 0], [0, 1, 1, 2, 1, 1, 0]])
mask = (users == 'Вадим') | (users == 'Илья')

print(visits[mask], end='\n\n')
print(visits[~mask])

[[1 1 2 0 1 0 1]
 [1 3 2 1 1 0 1]]

[[1 0 1 0 1 0 2]
 [0 1 2 2 1 0 0]
 [0 1 1 2 1 1 0]]


Можно вытягивать данные с помощью **прихотливой индексации**.
Алгоритм таков: передаем список/массив с индексами по которым надо вытащить значения. Индексы могут идти не по порядку.

In [40]:
import numpy as np

m = np.array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

print(m[[2, 4, 1], 1:], end='\n\n')
print(m[[0, 2, 4], [1, 2, 3]])

[[11 12 13 14]
 [21 22 23 24]
 [ 6  7  8  9]]

[ 1 12 23]


Функция **reshape** позволяет преобразовать массив данных в определенное кол-во подмассивов с нужным кол-вом элементов. В функцию передается кортеж, где первым элементом является кол-во строк, а втором кол-во столбцов, их произведение должно равнятся количеству всех элементов в исходном массиве

In [52]:
import numpy as np

m = np.arange(100)

print(m.reshape((5, 20)), end='\n\n') # двумерный вариант
print(m.reshape((5, 2, 10))) # трёхмерный вариант

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]

[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]]

 [[20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]

 [[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]]

 [[80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


### Задачи урока 2.7

1. На вход функции подается двумерный массив, доработайте функцию так чтобы она вернула маску по которой потом можно будет выбрать значения меньше 20 или больше 40.

![1](https://ucarecdn.com/49ccd304-d7b8-4203-9457-1cf4338b4056/)

In [87]:
import numpy as np

def solution(arr):
    mask = (arr < 20) | (arr > 40)
    return mask

2. На вход функции подается двумерный массив, доработайте функцию так чтобы она вернула значения, которые лежат на главной диагонали. Значения должны быть в одномерном массиве (Для особых знатоков: функцией diag не пользоваться!). Работайте с прихотливой индексацией.

![1](https://ucarecdn.com/62de17b8-9f2b-41e1-964e-736642e80acc/)

In [74]:
import numpy as np

def solution(arr):
    arr = arr[range(5), range(5)]
    return arr

3. На вход функции подается двумерный массив, доработайте функцию так чтобы она вернула значения, которые лежат на побочной диагонали. Значения должны быть в одномерном массиве array([1, 32, 84, 19, 20]) (Для особых знатоков: функцией diag не пользоваться!). Работайте с прихотливой индексацией.

![1](https://ucarecdn.com/3bb5b4e9-f8bf-4230-be95-304d24c5ae1f/)

In [86]:
import numpy as np

def solution(arr):
    arr = arr[range(4, -1, -1), range(5)]
    return arr

## 2.8 Практика: учимся изменять форму массива 

1. На вход подается одномерный массив, преобразуйте его в матрицу с 5 строками и 6 столбцами

In [ ]:
import numpy as np

def solution(arr):
    arr = np.reshape(5, 6)
    return arr

2.На вход подается одномерный массив, преобразуйте его в трехмерный массив, где каждая матрица будет размером 4х5 и таких матриц должно быть 10

In [ ]:
import numpy as np

def solution(arr):
    arr = arr.reshape(10, 4, 5)
    return arr

3. На вход подается двумерная матрица, вытяните из нее последние три строки, но так чтобы строки были расположены в обратном порядке:

![1](https://ucarecdn.com/6b649a66-c9ba-4949-851e-8e87820df813/)

![2](https://ucarecdn.com/6bcec988-10bc-4c44-ac3c-8c4ef5500c4a/)

In [13]:
import numpy as np

def solution(arr):
    arr = arr[[-1, -2, -3]]
    return arr


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

solution(m)

array([[ 1, 11,  1,  8,  6],
       [ 2, 32,  4, 31,  9],
       [ 4, 14, 84, 38, 11]])

3.  На вход подается двумерная матрица, вытяните из нее последние три строки, но так чтобы строки были расположены в обратном порядке. Затем возьмите только последние два столбца:

![1](https://ucarecdn.com/6b649a66-c9ba-4949-851e-8e87820df813/)

![2](https://ucarecdn.com/24a15cb1-a2be-4ef2-b551-bab7c8a1854f/)

In [39]:
import numpy as np

def solution(arr):
    arr = arr[2:, -2:][::-1]
    return arr


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

solution(m)

array([[ 1, 11,  1,  8,  6],
       [ 2, 32,  4, 31,  9],
       [ 4, 14, 84, 38, 11]])

4. На вход подается двумерная матрица размером 5х5. Преобразуйте ее в одномерный массив.

In [ ]:
import numpy as np

def solution(arr):
    arr = arr.reshape(-1)
    return arr

5. На вход подается трехмерная матрица размером 6х5х5. Преобразуйте ее в одномерный массив.

In [ ]:
import numpy as np

def solution(arr):
    arr = arr.reshape(-1)
    return arr

## 2.9 Еще о reshape, транспонирование, унарные и бинарные функции

При использовании **reshape** не создается новый объект, это ссылка на существующий объект

### Транспонирование

Для транспонирования используется функция **transpose()** или свойство **.T**

In [4]:
import numpy as np


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

print(m.transpose(), end='\n\n')
print(m.T)

[[10  8  4  2  1]
 [12 22 14 32 11]
 [14 18 84  4  1]
 [18 19 38 31  8]
 [20 12 11  9  6]]

[[10  8  4  2  1]
 [12 22 14 32 11]
 [14 18 84  4  1]
 [18 19 38 31  8]
 [20 12 11  9  6]]


### Унарные функции NumPy

In [11]:
import numpy as np

m = np.array([2, 4, 6, 8, 10])**2

print(np.sqrt(m)) # вычисление корня
print(np.abs(m)) # модуль
             

[ 2.  4.  6.  8. 10.]
[  4  16  36  64 100]


Округление значений:

In [18]:
import numpy as np

m = np.array([2.1, 2.2, 2.5, 2.6, 2.9])

print(np.round(m)) # обычное округление
print(np.ceil(m)) # в большую сторону
print(np.floor(m)) # в меньшую сторону


[2. 2. 2. 3. 3.]
[3. 3. 3. 3. 3.]
[2. 2. 2. 2. 2.]


В NumPy существует аналог None - **nan**, нужно быть осторожным так как он является объектом, соответственно при вызове функции len() длина массива будет выведена с учетом **nan**. Чтобы определить есть ли **nan** в массиве можно воспользоваться функцией **isnan()**:

In [24]:
import numpy as np

m = np.array([2, 4, 6, 8, 10, np.nan])

print(m)
print(len(m))
print(~np.isnan(m))

[ 2.  4.  6.  8. 10. nan]
6
[ True  True  True  True  True False]


### Бинарные функции NumPy

Бинарные функции - функции, которые могут принимать 2 массива

In [32]:
import numpy as np

m1 = np.array([2, 4, 6, 8, 10])
m2 = np.array([5, 4, 1, 2, 11])

print(np.maximum(m1, m2)) # максимальные значения из 2 массивов

[ 5  4  6  8 11]


## 2.10 Практика: закрепляем знания про унарные и бинарные функции

1. На вход подаётся матрица. Выполните ее транспонирование, а затем выполните возведение в квадрат каждого значения.

In [39]:
import numpy as np

def solution(arr):
    arr = arr.transpose()**2
    return arr


m = np.array([[2, 4, 6, 8, 10], [22, 44, 66, 88, 11]])
solution(m)

array([[   4,  484],
       [  16, 1936],
       [  36, 4356],
       [  64, 7744],
       [ 100,  121]])

2. На вход подаётся матрица. Вытяните первую и последнюю строчки. Сравните поэлементно две строчки и постройте новый одномерный массив, который будет состоять из минимальных значений. Например, если первый элемент первой строки больше чем первый элемент последней строки, то в результат должен пойти первый элемент последней строки. Тоже проделайте с остальными элементами.

In [47]:
import numpy as np

def solution(arr):
    return np.minimum(arr[0], arr[-1])


m = np.array([[2, 4, 6, 8, 10], 
              [22, 44, 66, 88, 11], 
              [82, 5, 9, 1, 14]])
solution(m)

array([ 2,  4,  6,  1, 10])

3. Прежде чем применять бинарную функцию на двух массивах, вы должны быть уверены, что ваши массивы имеют одинаковую размерность. На вход вашей функции подаётся два контейнера. Проверьте, равны ли размерности. Функция должна вернуть True, если размерности равны и False если нет. Попробуйте оттолкнуться от свойства shape. Посмотрите какие длины у кортежей и что за значения внутри них.

In [53]:
import numpy as np

def solution(a1, a2):
    return a1.shape == a2.shape


m1 = np.array([2, 4, 6, 8, 10])
m2 = np.array([5, 4, 1, 2, 11])

solution(m1, m2)

True

## 2.11 Логические функции и функция в функции, а еще where и статистика

Функция **where** принимает 3 аргумента - условие, значение если истина, значение если ложь. Таким образом можно, преобразовать значения массива в нужные нам данные

In [20]:
import numpy as np

m = np.array([2, 4, 5, 8, 10])

print(np.where(m % 2 == 0, 1, 0), end='\n\n')
print(np.where(m**2 > 25, np.sqrt(m), 100))


[1 1 0 1 1]

[100.         100.         100.           2.82842712   3.16227766]


Функция **where** аналогично работает и с двумерными массивами

In [21]:
import numpy as np

m = np.array([[2, 4, 6, 8, 10], [22, 44, 66, 88, 11]])

np.where(m > 5, m, 0)

array([[ 0,  0,  6,  8, 10],
       [22, 44, 66, 88, 11]])

### Статистические и математические функции

In [25]:
import numpy as np

m = np.array([2, 4, 5, 8, 10])

print(m.sum(), end='\n\n') # сумма 1 вариант записи
print(m.mean(), end='\n\n') # среднее 1 вариант записи

print(np.sum(m), end='\n\n') # сумма 2 вариант записи
print(np.mean(m), end='\n\n') # среднее 2 вариант записи

29

5.8

29

5.8



Если массив многомерный и необходимо произвести расчёт по строке или по столбцу отдельно, то можно передать в функцию именованный аргумент **axis**. Если **axis** равна 1, то суммируются строки, если равна 0, то суммируются столбцы

In [28]:
import numpy as np


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

print(m.sum(axis=1)) # суммирование всех значений по строке
print(m.mean(axis=0)) # среднее всех значений по столбцу

[ 74  79 151  78  27]
[ 5.  18.2 24.2 22.8 11.6]


**Другие полезные функции:**

In [50]:
import numpy as np


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

print(m.min(axis=0)) # минимальное значение по столбцам
print(m.max(axis=1)) # максимальное значение по строкам
print(m.var()) # дисперсия
print(m.std()) # стандартное отклонение
print(m.argmin(axis=0)) # индекс минимального значения по столбцу
print(m.argmax()) # индекс максимального значения

[ 1 11  1  8  6]
[20 22 84 32 11]
279.67040000000003
16.723348946906537
[4 4 4 4 4]
12


### Задачи урока 2.11

1. На вход подаётся два одномерных массива. Сравните их поэлементно: постройте новый массив из минимальных значений. У нового одномерного массива найдите максимальное значение

In [55]:
import numpy as np

def solution(m1, m2):
    return np.minimum(m1, m2).max()

m1 = np.array([2, 4, 6, 8, 10])
m2 = np.array([5, 4, 1, 2, 11])

solution(m1, m2)

10

2. На вход подаётся два одномерных массива. Сравните их поэлементно. Постройте новый массив из максимальных значений. У нового одномерного массива найдите минимальное значение

In [62]:
import numpy as np

def solution(m1, m2):
    return np.where(m1 > m2, m1, m2).min()


m1 = np.array([2, 4, 6, 8, 10])
m2 = np.array([5, 4, 1, 2, 11])

solution(m1, m2)

4

3. На вход подаётся одномерный массив. Найдите среднее значение.

In [63]:
import numpy as np

def solution(m1):
    return m1.mean()


m1 = np.array([2, 4, 6, 8, 10])

## 2.12 Практика: доводим до мастерства работу с полезными функциями

1. На вход подается матрица. Посчитайте минимальные значения по каждому столбцу

In [70]:
import numpy as np

def solution(m2d):
    return m2d.min(axis=0)


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])
solution(m)

array([ 1, 11,  1,  8,  6])

2. На вход подается матрица. Посчитайте максимальные значения по каждой строке

In [71]:
import numpy as np

def solution(m2d):
    return m2d.max(axis=1)


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])
solution(m)

array([20, 22, 84, 32, 11])

3. Ранее пройденная задача, но попробуем решить ее снова:

    На вход подается одномерный массив в котором хранится информация о количестве картофеля на каждом складе (всего 4 склада). Посчитайте для каждого склада, сколько процентов картофеля от общего количества хранится на каждом складе. Общее количество картофеля на всех складах (определите сами через функцию). Не забудьте что каждое значение надо умножить на 100.
Округлять значения не требуется! Знак процента тоже добавлять не следует. Просто выполните арифметические операции.

In [74]:
import numpy as np

def solution(m1d):
    return m1d / m1d.sum() * 100


m = np.array([2, 4, 6, 8, 10])
solution(m)

array([ 6.66666667, 13.33333333, 20.        , 26.66666667, 33.33333333])

4. Вам передан одномерный массив. Если значение меньше или равно нулю, то замените его на нуль. Если значение больше нуля, то замените на 1.

In [76]:
import numpy as np

def solution(m1d):
    return np.where(m1d <= 0, 0, 1)


m = np.array([2, 4, 6, 8, 10])
solution(m)

array([1, 1, 1, 1, 1])

5. Вам передана матрица. Если значение меньше или равно нулю, то замените его на нуль. Остальное не трогать)

In [84]:
import numpy as np

def solution(m1d):
    return np.where(m1d <=0, 0, m1d)


m = np.array([2, 4, 6, 8, 10])
solution(m)

array([ 0,  4,  6,  8, 10])

6. Вам передана матрица. Если значение меньше нуля, то возьмите его по модулю. Если значение больше нуля, то извлеките из него квадратный корень.

In [108]:
import numpy as np

def solution(m1d):
    return np.where(m1d < 0, np.abs(m1d), np.sqrt(m1))


m = np.array([-2, 4, 6, 8, 10])
solution(m)

array([2.        , 2.        , 2.44948974, 2.82842712, 3.16227766])

7. На вход подается матрица. Для каждого столбца определите индекс строки в которой содержится минимальное значение.

In [112]:
import numpy as np

def solution(m2d):
    return m2d.argmin(axis=0)


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])
solution(m)

array([4, 4, 4, 4, 4], dtype=int64)

8. На вход подается матрица. Для каждой строки определите индекс столбца в котором содержится максимальное значение.

In [114]:
import numpy as np

def solution(m2d):
    return m2d.argmax(axis=1)


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])
solution(m)

array([4, 1, 2, 1, 1], dtype=int64)

## 2.13 Функции any, all, sort, unique, in1d. Обзор линейной алгебры

Функция **any** возвращает Truе, если в массиве есть хоть одно значение равное True, а False в остальных случаях. Функция **all** возвращает Truе, если в массиве все значения равны True и False в остальных случаях.

In [7]:
import numpy as np

m = np.array([2, 4, 6, 8, 10])

print(any(m < 0))
print(all(m > 0))

False
True


Функция **sort** сортирует массив "на месте" не возваращая массива

In [10]:
import numpy as np

m = np.array([10, 2, 4, 6, 8])
m.sort()

print(m)

[ 2  4  6  8 10]


Если массив многомерный, то по умолчанию сортировка идёт по строкам

In [16]:
import numpy as np

m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

m.sort()
print(m) # сортировка по строке

[[10 12 14 18 20]
 [ 8 12 18 19 22]
 [ 4 11 14 38 84]
 [ 2  4  9 31 32]
 [ 1  1  6  8 11]]


In [17]:
import numpy as np

m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

m.sort(0)
print(m) # сортировка по столбцам

[[ 1 11  1  8  6]
 [ 2 12  4 18  9]
 [ 4 14 14 19 11]
 [ 8 22 18 31 12]
 [10 32 84 38 20]]


Функция **unique** чистит массив от дубликатов и сортирует данные по возрастанию, что-то типа **set** от стандартного питона

In [20]:
import numpy as np

names = np.array(['Вадим', 'Вадим', 'Артём'])

np.unique(names)

array(['Артём', 'Вадим'], dtype='<U5')

Функция **in1d** позволяет найти нужные значения в массиве с помощью передачи любой последовательности (список, кортеж и т.д.)

In [30]:
import numpy as np

m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

np.in1d(m, [1, 2])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False,  True, False,  True, False, False])

Функции линейной алгебры:

In [42]:
import numpy as np

m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])

print(np.dot(m.transpose(), m), end='\n\n') # перемножение матриц
print(np.linalg.det(m), end='\n\n') # детерминант
print(np.diag(m), end='\n\n') # вывод элементов главной диагонали
print(np.triu(m), end='\n\n') # вывод верхнего треугольника матрицы
print(np.tril(m), end='\n\n') # вывод нижнего треугольника матрицы

[[ 185  427  629  554  364]
 [ 427 1969 1879 2246 1012]
 [ 629 1879 7593 3918 1462]
 [ 554 2246 3918 3154 1333]
 [ 364 1012 1462 1333  782]]

852104.0000000016

[10 22 84 31  6]

[[10 12 14 18 20]
 [ 0 22 18 19 12]
 [ 0  0 84 38 11]
 [ 0  0  0 31  9]
 [ 0  0  0  0  6]]

[[10  0  0  0  0]
 [ 8 22  0  0  0]
 [ 4 14 84  0  0]
 [ 2 32  4 31  0]
 [ 1 11  1  8  6]]



Если необходимо инициализировать массив случайными числами, то можно использовать пакет **random** в бибилиотке NumPy

In [48]:
import numpy as np

m1 = np.random.randint(1, 101, size=5) # генерация 5 случайных чисел в одномерной массиве
m2 = np.random.randint(1, 101, size=(5, 10)) # генерация 5 массивов с 10 случайными числами

print(m1, end='\n\n')
print(m2)

[50 61 71 12 76]

[[69 23 59 34 54 25 33 62 37 99]
 [44 13 88 46 11 38 46 19 27 72]
 [53 73 35 36 20 37 26 66 64 17]
 [13 67 15 26 94 87 32 30 27 99]
 [15 48 38 96 32 63 87 57 30 48]]


### Задачи урока 2.13

1. На вход подаётся одномерный массив типа np.bool. Функция должна вернуть True если все значения в массиве равны False. Иначе функция должна вернуть False.

In [52]:
import numpy as np

def solution(m1d):
    return all(~m)


m = np.array([False, True])
solution(m)

False

2. На вход подаётся матрица. Посчитайте сумму элементов верхнего треугольника:

![1](https://ucarecdn.com/934e33ab-ab16-4063-a600-267384dcdd03/)

In [59]:
import numpy as np

def solution(m2d):
    return np.triu(m2d).sum()


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])
solution(m)

324

3. На вход подаётся одномерный массив. Посчитайте количество уникальных значений.

In [65]:
import numpy as np

def solution(m1d):
    return len(np.unique(m1d))


m = np.array([[10, 12, 14, 18, 20],
              [8, 22, 18, 19, 12],
              [4, 14, 84, 38, 11],
              [2, 32, 4, 31, 9],
              [1, 11, 1, 8, 6]])
solution(m)

18

## 2.14 Функции permutation и shuffle. Сохранение массива в файл

Функция **permutation** позволяет сгенерировать массив внтури которого будут перемешаны значения в случайном порядке

In [73]:
import numpy as np

m = np.random.permutation(5)

print(m)

[4 3 2 0 1]


Функция **shuffle** позволяет перемешать уже существующий массив

In [72]:
import numpy as np

m = np.array([1, 2, 3, 4, 5])
np.random.shuffle(m)

print(m)

[4 1 3 5 2]


Функция **randn** генерирует случайные числа типа **float**, которые имеют нормально распределение

In [106]:
import numpy as np

m1 = np.random.randn(10) # одномерный массив
m2 = np.random.randn(2, 5) # двумерный массив

print(m1, end='\n\n')
print(m2)

[ 1.39411511 -1.27552359  1.29975252  1.12035835 -1.40983589  2.01396861
  0.51446084 -1.21590665 -0.02071283 -0.30366904]

[[-0.73168258 -0.6283983  -1.5969641   0.36131154 -0.79229258]
 [ 0.30441886  0.61343465 -0.8268409   0.70540189  0.14775543]]


Чтобы записать массив необходмо использовать функцию **save**, а чтобы загрузить его **load**

In [112]:
import numpy as np

m1 = np.random.randn(10) # одномерный массив
m2 = np.random.randn(2, 5) # двумерный массив

np.save('rdk.npy', m1)
np.load('rdk.npy')

array([ 1.2357292 ,  0.28742663, -0.64458895,  1.25433802,  0.73822406,
        0.24176962,  1.10710045,  1.66294941,  0.31559417,  0.05407744])

Чтобы записать несколько массивов необходмо использовать функцию **savez**. Если необходимо сжать данные, то можно использвать **savez_compressed**

In [126]:
import numpy as np

m1 = np.random.randn(10) # одномерный массив
m2 = np.random.randn(2, 5) # двумерный массив

np.savez('arrays', name1=m1, name2=m2)

m = np.load('arrays.npz')
m['name1']

array([ 1.10516167, -0.75884957, -1.5716967 , -0.32711621,  0.7811125 ,
       -0.22071066, -1.44354515,  0.8899862 ,  1.5403879 , -0.50879677])

## ВСЕ ПРОЙДЕННЫЕ ФУНКЦИИ

np.array() | создание массива.

np.zeros() | создание массива, заполненного нулями.

np.ones() | создание массива, заполненного единицами.

np.full() | создает массив с заданными значениями.

np.sqrt() | взятие квадратного корня.

np.abs() | взятие по модулю.

np.round() | округление.

np.ceil() | округление в большую сторону.

np.floor() | округление в меньшую сторону.

np.nan() | значение пропущено(NaN).

np.isnan() | проверка, что значение пропущено.

аргумент out | доп. параметр, указывающий куда нужно записать результат(переменная).

np.maximum() | сравнение двух массивов >.

np.minimum() | сравнение двух массивов <.

np.subtract() | вычитание двух массивов.

np.add() | сложение двух массивов.

np.multiply() | умножение двух массивов.

np.divide() | деление двух массивов.

np.isinf() | проверка на inf(деление на нуль).

np.greater() | сравнение двух массивов >.

np.greater_equal() | сравнение двух массивов >=.

np.less() | сравнение двух массивов <.

np.less_equal() | сравнение двух массивов <=.

np.equal() | сравнение двух массивов ==.

np.not_equal() | сравнение двух массивов !=.

np.sum() | суммирует все элементы в массиве.

np.mean() | среднее значение.

np.min() | минимальное значение.

np.max() | максимальное значение.

np.argmin() | индекс минимального значения в массиве.

np.argmax() | индекс максимального значения в массиве.

np.std() | стандартное отклонение.

np.var() | дисперсия.

аргумент axis(ось) | принимает значение 1 или 0. 

     Пример axis в функции np.sum() | axis=1 - значит подсчет по все строке, axis = 0 - значит подсчет по каждому столбцу.

np.unique() | возвращает массив уникальных значений.

np.in1d() | проверка на сущ. элемента в массиве.

np.dot() | перемножение матриц.

np.linalg.det() | детерминант.

np.linalg.inv() | обратная матрица.

np.diag() | значения с главной диагонали.

np.triu() | верхний треугольник(матрица).

np.tril() | нижний треугольник(матрица).

np.trace() | вычисляет cумму диагональных элементов (след) матрицы.

np.where() | задает условие, создает новый массив.

аргумент k(np.diag(), np.triu(), np.tril()) | смещение.

аргумент offset(np.trace()) | смещение.

np.random.randint() | массив случайных целых чисел.

np.random.permutation() | перемешивание массива, возвращает массив.

np.random.shuffle() | перемешивание массива, изменяет  массив,  не возвращает массив.

np.random.randn() | массив случайных значений с нормальным распределением.

np.save() | сохранение массива(.npy).

np.savez() | сохранение нескольких массивов(.npz).

np.load() | чтение массива.

np.savez_compressed() | cохраняет несколько массивов в сжатом файле(.npz).

arr.shape() | возвращает размер arr.

arr.dtype() | возвращает тип элементов arr.

arr.ndim() | возвращает кол-во измерений в массиве.

arr.astype() | выполняет преобразование типов, вернет новый массив.

arr.copy() | копирование.

arr.reshape() | выполняет преобразование массива, не создает новый массив, трансформирует старый.

arr.T или arr.transpose() | транспонирование, не копирует.

значок тильда ~

arr.any() | поиск в массиве хотя бы одного True.

arr.all() | проверка, что все элементы массива True

arr.sort() | сортировка, (при такой записи)не возвращает, сортирует исходный массив